name: Pulumi Preview
permissions:
  id-token: write
  contents: write
  actions: write
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "my-k8s-pulumi/**"

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        stack: [base, dev, qa, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Pulumi Deps
        working-directory: src
        run: yarn install --frozen-lockfile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::139539663033:role/gha_role-8206eea
      - name: Run Pulumi Preview
        uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: preview
          diff: true
          stack-name: peopleticker/${{ matrix.stack }}
          work-dir: src
